version: '2.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: gastodb
      POSTGRES_USER: gestor
      POSTGRES_PASSWORD: gestorpassword
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres

volumes:
  postgres_data:
